name: control_instalaciones
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.7
  table_calendar: ^3.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/planos/plano_casa.svg